### ISSUE TITLE
USB Bluetooth adapter 

### ISSUE THREAD

**Issue by martach** [icanos/hassio-plejd#101] opened 2020-08-13 08:26 UTC
Maybe not exactly an issue, but I have had troubles getting this plugin to work with a USB Bluetooth adapter (Asus bt400). I eventually gave up and returned the adapter. Does anyone have a clue about what Bluetooth adapter to buy?

**Comment by martach** [comment] 2020-08-18 15:11
I tried again with ASUS BT500. Unfortunately, it is still not working. Any ideas how to resolve this? This is the log:

> [services.d] starting services
> [services.d] done.
> [17:04:52] INFO: Starting the Plejd service...
> [17:04:52] INFO: Verified permissions on startup script
> [17:04:52] INFO: Executing startup script
> [17:04:53] INFO: Wrote plejd.json
> [17:04:53] INFO: Running add-on
> starting Plejd add-on v. 0.4.7
> plejd-api: login()
> plejd-api: logging into [XXXXXXXXXX]
> plejd-api: got session token response
> plejd-api: getSites()
> plejd-api: got site list response
> plejd-api: getSite(...)
> plejd-api: got site details response
> wireEvents()
> init()
> plejd-mqtt: connected to mqtt.
> plejd-mqtt: discovered light (DIM-01) named Köksö with PID 21.
> plejd-mqtt: discovered light (DIM-01) named Köks-L with PID 11.
> plejd-mqtt: discovered light (DIM-01) named Spottar övre badrum with PID 16.
> plejd-mqtt: discovered light (DIM-01) named Spottar nedre badrum with PID 26.
> plejd-mqtt: discovered light (DIM-01) named Köksbord with PID 30.
> plejd-mqtt: discovered light (DIM-01) named hörn kök/lekrum with PID 31.
> plejd-mqtt: discovered light (DIM-01) named Kamin with PID 33.
> plejd-mqtt: discovered light (DIM-01) named Johans rum with PID 36.
> plejd-mqtt: discovered light (DIM-01) named Teve with PID 34.
> plejd-mqtt: discovered switch (Scene) named Ljust with PID 1.
> plejd-mqtt: discovered switch (Scene) named Mörkt with PID 3.
> plejd-mqtt: discovered switch (Scene) named Middag with PID 2.
> plejd-mqtt: discovered switch (Scene) named Mys vardagsrum with PID 6.
> plejd-mqtt: discovered switch (Scene) named Läsa soffa with PID 5.
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.
> init()
> plejd-ble: connecting to /org/bluez/hci0/dev_EB_04_14_BB_A1_04
> plejd-ble: warning: unable to connect, will retry. DBusError: Software caused connection abort
> onDeviceConnected()
> plejd-ble: warning: wasn't able to connect to Plejd, will retry.
> plejd-ble: were unable to connect, will retry connection in 10 seconds.

**Comment by SweVictor** [comment] 2021-01-27 07:59
Can't say it's the best, but I at least have things running with the Deltaco BT-118 (sold by m.nu) under Windows => VirtualBox => HassIO. Have replaced Windows drivers using Zadig, so that might something to try if you have a similar setup.

**Comment by faanskit** [comment] 2021-05-12 12:36
Cannot reproduce. The following system works fine for me:

- ASUS BT400, OOTB Firmware and OOTB Windows drivers
- Virtualbox, 6.1, Windows 10 Host
- Hassio 2021.5.2, [Virtualbox VDI](https://www.home-assistant.io/installation/windows)
- Addon 8.0.0-develop (Have not tried other versions)

Sometimes during startup of the vurtual device, BT device is not properly attached.
Right click on USB icon and ensure "Broadcom Corp BCM920702 Bluetooth 4.0 [xxx]" is selected.

**Comment by SweVictor** [comment] 2021-05-17 07:09
Alright, I'm closing this for now then. Please update to v0.8.X or later (currently in develop branch) if the problem persists.

**Closed by SweVictor** 2021-05-17 07:09 UTC
