### ISSUE TITLE
Can't install R pi3+

### ISSUE THREAD

**Issue by 4xJ** [icanos/hassio-plejd#62] opened 2020-02-13 07:31 UTC
Hi!
I have problem after I update the HassOs to 3.10 and Hassio version to 0.105.3.

After that the add-on won't start and I delete and reinstall but the install generate this error:
20-02-13 07:16:42 INFO (SyncWorker_0) [hassio.docker.addon] Start build 4cb18a39/armv7-addon-plejd:0.3.4
20-02-13 07:18:40 ERROR (SyncWorker_0) [hassio.docker.addon] Can't build 4cb18a39/armv7-addon-plejd:0.3.4: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies   g++=8.3.0-r0   gcc=8.3.0-r0   libc-dev=0.7.1-r0   linux-headers=4.19.36-r0   make=4.2.1-r2   python=2.7.16-r2   bluez=5.50-r3   eudev-dev=3.2.8-r0     && apk add --no-cache   git   nodejs=10.16.3-r0   npm=10.16.3-r0   dbus-dev   glib-dev     && npm config set unsafe-perm true' returned a non-zero code: 2
20-02-13 07:18:40 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<AddonManager.install() done, defined at /usr/src/hassio/hassio/addons/__init__.py:106> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/addons/__init__.py", line 135, in install
    raise AddonsError() from None
hassio.exceptions.AddonsError

What can I do?

**Comment by gust1n** [comment] 2020-02-13 16:12
Duplicate of #60

**Comment by icanos** [comment] 2020-02-14 11:14
This should be resolved with the latest version, please try that.

**Comment by icanos** [comment] 2020-02-14 11:39
Fixed in latest version

**Closed by icanos** 2020-02-14 11:39 UTC
