### ISSUE TITLE
Brightness level incorrect when changing with RTR-01 or WPH-01

### ISSUE THREAD

**Issue by ankisch** [icanos/hassio-plejd#138] opened 2021-01-13 20:30 UTC
Hi, thanks for a great addon.

Could not find any issue regarding this so here goes.

When I use RTR-01 or WPH-01 to change the brightness level the lights brightness attribute in HA jumps all over the place. It jumps 60 points both ways when I change one "tick" on the dimmer. If I dim down past 0 it just "restarts" from 255 again. It's almost like the brightness-slider on "more-info" is just a zoomed in part of the whole slider.

When I change the brightness from HA everything works just fine and brightness_pct is the same as in Plejd app.

I tried changing the dim start and dim max levels in load settings in the Plejd app, but the behaviour remains the same.

The logs provide me with no clues as I can't see anything that is happening as a result of a button press or dimmer turn.

```
...
plejd-api: got site details response
wireEvents()
init()
plejd-ble: disconnecting /org/bluez/hci0/dev_##_##_##_##_##_##
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named Trapphall tak with PID 11.
plejd-mqtt: discovered light (DIM-01) named Kök tak with PID 13.
plejd-mqtt: discovered light (DIM-01) named Kök bänk with PID 14.
plejd-mqtt: discovered light (DIM-02) named Kök fönster with PID 16.
plejd-mqtt: discovered light (DIM-02) named Kök bord with PID 15.
plejd-mqtt: discovered switch (WPH-01) named Kök knapp vä with PID 17.
plejd-mqtt: discovered switch (WPH-01) named Kök knapp hö with PID 18.
plejd-mqtt: discovered light (DIM-01) named Hall tak with PID 20.
plejd-mqtt: discovered light (DIM-02) named Vardagsrum fönster with PID 22.
plejd-mqtt: discovered light (DIM-02) named Vardagsrum tak with PID 21.
plejd-mqtt: discovered switch (WPH-01) named Vardagsrum mot hall knapp vä with PID 24.
plejd-mqtt: discovered switch (WPH-01) named Vardagsrum mot hall knapp hö with PID 25.
plejd-mqtt: discovered light (DIM-01) named Tvättstuga tak with PID 27.
plejd-mqtt: discovered light (DIM-02) named Badrum nere spegel with PID 30.
plejd-mqtt: discovered light (DIM-02) named Badrum nere tak with PID 29.
plejd-mqtt: discovered light (DIM-02) named Allrum tak ost with PID 34.
plejd-mqtt: discovered light (DIM-02) named Trappa tak with PID 33.
plejd-mqtt: discovered switch (WPH-01) named Allrum syd knapp vä with PID 35.
plejd-mqtt: discovered switch (WPH-01) named Allrum syd knapp hö with PID 57.
plejd-mqtt: discovered switch (WPH-01) named Trapp uppe knapp vä with PID 36.
plejd-mqtt: discovered switch (WPH-01) named Trapp uppe knapp hö with PID 37.
plejd-mqtt: discovered switch (WPH-01) named Trapp nere knapp vä with PID 38.
plejd-mqtt: discovered switch (WPH-01) named Trapp nere knapp hö with PID 39.
plejd-mqtt: discovered light (DIM-02) named Barnrum fönster with PID 42.
plejd-mqtt: discovered light (DIM-02) named Barnrum tak with PID 41.
plejd-mqtt: discovered switch (WPH-01) named Barnrum knapp vä with PID 43.
plejd-mqtt: discovered switch (WPH-01) named Barnrum knapp hö with PID 44.
plejd-mqtt: discovered light (DIM-02) named Badrum uppe tak with PID 46.
plejd-mqtt: discovered light (DIM-02) named Badrum uppe spegel with PID 47.
plejd-mqtt: discovered light (DIM-02) named Kontor fönster with PID 49.
plejd-mqtt: discovered light (DIM-02) named Kontor tak with PID 50.
plejd-mqtt: discovered switch (WPH-01) named Kontor knapp vä with PID 51.
plejd-mqtt: discovered switch (WPH-01) named Kontor knapp hö with PID 52.
plejd-mqtt: discovered light (DIM-02) named Allrum fönster with PID 53.
plejd-mqtt: discovered light (DIM-02) named Allrum tak väst with PID 54.
plejd-mqtt: discovered switch (WPH-01) named Allrum vid sovrum knapp vä with PID 55.
plejd-mqtt: discovered switch (WPH-01) named Allrum vid sovrum knapp hö with PID 56.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-01) named Trapphall tak with PID 11.
plejd-mqtt: discovered light (DIM-01) named Kök tak with PID 13.
plejd-mqtt: discovered light (DIM-01) named Kök bänk with PID 14.
plejd-mqtt: discovered light (DIM-02) named Kök fönster with PID 16.
plejd-mqtt: discovered light (DIM-02) named Kök bord with PID 15.
plejd-mqtt: discovered switch (WPH-01) named Kök knapp vä with PID 17.
plejd-mqtt: discovered switch (WPH-01) named Kök knapp hö with PID 18.
plejd-mqtt: discovered light (DIM-01) named Hall tak with PID 20.
plejd-mqtt: discovered light (DIM-02) named Vardagsrum fönster with PID 22.
plejd-mqtt: discovered light (DIM-02) named Vardagsrum tak with PID 21.
plejd-mqtt: discovered switch (WPH-01) named Vardagsrum mot hall knapp vä with PID 24.
plejd-mqtt: discovered switch (WPH-01) named Vardagsrum mot hall knapp hö with PID 25.
plejd-mqtt: discovered light (DIM-01) named Tvättstuga tak with PID 27.
plejd-mqtt: discovered light (DIM-02) named Badrum nere spegel with PID 30.
plejd-mqtt: discovered light (DIM-02) named Badrum nere tak with PID 29.
plejd-mqtt: discovered light (DIM-02) named Allrum tak ost with PID 34.
plejd-mqtt: discovered light (DIM-02) named Trappa tak with PID 33.
plejd-mqtt: discovered switch (WPH-01) named Allrum syd knapp vä with PID 35.
plejd-mqtt: discovered switch (WPH-01) named Allrum syd knapp hö with PID 57.
plejd-mqtt: discovered switch (WPH-01) named Trapp uppe knapp vä with PID 36.
plejd-mqtt: discovered switch (WPH-01) named Trapp uppe knapp hö with PID 37.
plejd-mqtt: discovered switch (WPH-01) named Trapp nere knapp vä with PID 38.
plejd-mqtt: discovered switch (WPH-01) named Trapp nere knapp hö with PID 39.
plejd-mqtt: discovered light (DIM-02) named Barnrum fönster with PID 42.
plejd-mqtt: discovered light (DIM-02) named Barnrum tak with PID 41.
plejd-mqtt: discovered switch (WPH-01) named Barnrum knapp vä with PID 43.
plejd-mqtt: discovered switch (WPH-01) named Barnrum knapp hö with PID 44.
plejd-mqtt: discovered light (DIM-02) named Badrum uppe tak with PID 46.
plejd-mqtt: discovered light (DIM-02) named Badrum uppe spegel with PID 47.
plejd-mqtt: discovered light (DIM-02) named Kontor fönster with PID 49.
plejd-mqtt: discovered light (DIM-02) named Kontor tak with PID 50.
plejd-mqtt: discovered switch (WPH-01) named Kontor knapp vä with PID 51.
plejd-mqtt: discovered switch (WPH-01) named Kontor knapp hö with PID 52.
plejd-mqtt: discovered light (DIM-02) named Allrum fönster with PID 53.
plejd-mqtt: discovered light (DIM-02) named Allrum tak väst with PID 54.
plejd-mqtt: discovered switch (WPH-01) named Allrum vid sovrum knapp vä with PID 55.
plejd-mqtt: discovered switch (WPH-01) named Allrum vid sovrum knapp hö with PID 56.
plejd-ble: connecting to /org/bluez/hci0/dev_##_##_##_##_##_##
onDeviceConnected()
trying 10 characteristics
authenticate()startPing()
startWriteQueue()
```

**Comment by icanos** [comment] 2021-01-14 08:06
Could you perhaps try to rebuild the addon using the latest changes? There was quite a big update to all the on/off/transition logic merged last night.

**Comment by ankisch** [comment] 2021-01-14 08:37
Rebuilt but experiencing the same behavior. Attaching a short film shot with my phone that shows what happens in HA when using RTR-01.

If it matters the light in question is using LED trailing edge with dim start 31% and dim max 65%. Using Intel NUC with HassOS 5.10 and HA 2021.1.0.

https://user-images.githubusercontent.com/52548910/104564641-762b0980-564b-11eb-8d22-afa3798bcfa9.mp4

**Comment by f00dagi** [comment] 2021-01-18 17:38
>Could you perhaps try to rebuild the addon using the latest changes? There was quite a big update to all the on/off/transition logic merged last night.

@icanos Hi, how do I get all those updates into my system. I see no update for the addon in the supervisor. Still 0.4.8? Thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SweVictor** [comment] 2021-01-24 14:49
@f00dagi and others: You would need to uninstall the "official" addon and install the addon manually instead.

If you are going to try to debug stuff I would recommend waiting until at least #149 is merged, or get the code from that branch instead. You would then be able to set logging to info/debug/verbose/silly without any code changes.

Regarding the original issue: Do the changes update correctly in the Plejd app? As a second thing there is also a difference in Plejd between the RTR and the load, those are not the same device. Not saying that is the cause, just a thought.

**Comment by ankisch** [comment] 2021-01-24 14:56
> Regarding the original issue: Do the changes update correctly in the Plejd app? As a second thing there is also a difference in Plejd between the RTR and the load, those are not the same device. Not saying that is the cause, just a thought.

Yes, changes in the Plejd app are correct and follows the dimmer.

**Comment by f00dagi** [comment] 2021-01-26 07:10
> 
> 
> @f00dagi and others: You would need to uninstall the "official" addon and install the addon manually instead.
> 
> If you are going to try to debug stuff I would recommend waiting until at least #149 is merged, or get the code from that branch instead. You would then be able to set logging to info/debug/verbose/silly without any code changes.
> 
> Regarding the original issue: Do the changes update correctly in the Plejd app? As a second thing there is also a difference in Plejd between the RTR and the load, those are not the same device. Not saying that is the cause, just a thought.

@SweVictor: Thanks! When do you think all the changes done related to transition and brightness will be released in the official addon? In the near future?

**Comment by SweVictor** [comment] 2021-01-26 09:41
We're discussing when/how to release here #150, can't say a date  unfortunately.

**Comment by SweVictor** [comment] 2021-01-30 09:12
0.5.0 released! @f00dagi please update when possible, turn on verbose logging and report back if the problem persists. Thanks!

**Comment by f00dagi** [comment] 2021-01-30 12:11
> 0.5.0 released! @f00dagi please update when possible, turn on verbose logging and report back if the problem persists. Thanks!

@SweVictor: I updated and initial testing of brightness and transition show wonderful results! Thanks for putting energy, competence and time into this. I can now continue to improve the automatic smooth change of light level in my house!

**Comment by SweVictor** [comment] 2021-01-30 13:30
Great to hear, thanks for reporting back! Closing for now.

**Closed by SweVictor** 2021-01-30 13:30 UTC

**Comment by ankisch** [comment] 2021-01-30 16:05
Don't know if @f00dagi had the same problem as me, but I still have the same problem as shown in the video.

Turned on verbose logging and tried two different RTR-01 and DIM-01

```
2021-01-30 16:56:03 VRB [plejd-ble] Raw event received: 0e011000980188ba
2021-01-30 16:56:03 VRB [plejd-ble] Device 14, cmd 0098, state 1, dim/data2 136
2021-01-30 16:56:03 DBG [plejd-ble] Kök bänk (14) got state+dim update. S: 1, D: 136
2021-01-30 16:56:03 VRB [plejd-mqtt] Updating state for Kök bänk: 1, dim: 136
2021-01-30 16:56:03 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":171},"14":{"state":1,"dim":136},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:03 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/14/state - {"state":"ON","brightness":136}
2021-01-30 16:56:03 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/14/availability - online
2021-01-30 16:56:03 VRB [plejd-ble] Raw event received: 0e01100098014cb0
2021-01-30 16:56:03 VRB [plejd-ble] Device 14, cmd 0098, state 1, dim/data2 76
2021-01-30 16:56:03 DBG [plejd-ble] Kök bänk (14) got state+dim update. S: 1, D: 76
2021-01-30 16:56:03 VRB [plejd-mqtt] Updating state for Kök bänk: 1, dim: 76
2021-01-30 16:56:03 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":171},"14":{"state":1,"dim":76},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:03 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/14/state - {"state":"ON","brightness":76}
2021-01-30 16:56:03 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/14/availability - online
2021-01-30 16:56:03 VRB [plejd-ble] Raw event received: 0e01100098019891
2021-01-30 16:56:03 VRB [plejd-ble] Device 14, cmd 0098, state 1, dim/data2 152
2021-01-30 16:56:03 DBG [plejd-ble] Kök bänk (14) got state+dim update. S: 1, D: 152
2021-01-30 16:56:03 VRB [plejd-mqtt] Updating state for Kök bänk: 1, dim: 152
2021-01-30 16:56:03 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":171},"14":{"state":1,"dim":152},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:03 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/14/state - {"state":"ON","brightness":152}
2021-01-30 16:56:03 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/14/availability - online
2021-01-30 16:56:03 VRB [plejd-ble] Raw event received: 0e0110009801207d
2021-01-30 16:56:03 VRB [plejd-ble] Device 14, cmd 0098, state 1, dim/data2 32
2021-01-30 16:56:03 DBG [plejd-ble] Kök bänk (14) got state+dim update. S: 1, D: 32
2021-01-30 16:56:03 VRB [plejd-mqtt] Updating state for Kök bänk: 1, dim: 32
2021-01-30 16:56:03 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":171},"14":{"state":1,"dim":32},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:03 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/14/state - {"state":"ON","brightness":32}
2021-01-30 16:56:03 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/14/availability - online
2021-01-30 16:56:04 VRB [plejd-ble] Raw event received: 0e0110009801a868
2021-01-30 16:56:04 VRB [plejd-ble] Device 14, cmd 0098, state 1, dim/data2 168
2021-01-30 16:56:04 DBG [plejd-ble] Kök bänk (14) got state+dim update. S: 1, D: 168
2021-01-30 16:56:04 VRB [plejd-mqtt] Updating state for Kök bänk: 1, dim: 168
2021-01-30 16:56:04 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":171},"14":{"state":1,"dim":168},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:04 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/14/state - {"state":"ON","brightness":168}
2021-01-30 16:56:04 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/14/availability - online
2021-01-30 16:56:04 VRB [plejd-ble] Raw event received: 0d011000980105bb
2021-01-30 16:56:04 VRB [plejd-ble] Device 13, cmd 0098, state 1, dim/data2 5
2021-01-30 16:56:04 DBG [plejd-ble] Kök tak (13) got state+dim update. S: 1, D: 5
2021-01-30 16:56:04 VRB [plejd-mqtt] Updating state for Kök tak: 1, dim: 5
2021-01-30 16:56:04 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":5},"14":{"state":1,"dim":168},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:04 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/13/state - {"state":"ON","brightness":5}
2021-01-30 16:56:04 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/13/availability - online
2021-01-30 16:56:05 VRB [plejd-ble] Raw event received: 0e0110009801a86800
2021-01-30 16:56:05 VRB [plejd-ble] Device 14, cmd 0098, state 1, dim/data2 168
2021-01-30 16:56:05 DBG [plejd-ble] Kök bänk (14) got state+dim update. S: 1, D: 168
2021-01-30 16:56:05 VRB [plejd-mqtt] Updating state for Kök bänk: 1, dim: 168
2021-01-30 16:56:05 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":5},"14":{"state":1,"dim":168},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:05 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/14/state - {"state":"ON","brightness":168}
2021-01-30 16:56:05 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/14/availability - online
2021-01-30 16:56:05 VRB [plejd-ble] Raw event received: 0d0110009801c9b0
2021-01-30 16:56:05 VRB [plejd-ble] Device 13, cmd 0098, state 1, dim/data2 201
2021-01-30 16:56:05 DBG [plejd-ble] Kök tak (13) got state+dim update. S: 1, D: 201
2021-01-30 16:56:05 VRB [plejd-mqtt] Updating state for Kök tak: 1, dim: 201
2021-01-30 16:56:05 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":201},"14":{"state":1,"dim":168},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:05 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/13/state - {"state":"ON","brightness":201}
2021-01-30 16:56:05 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/13/availability - online
2021-01-30 16:56:05 VRB [plejd-ble] Raw event received: 0d01100098016fa1
2021-01-30 16:56:05 VRB [plejd-ble] Device 13, cmd 0098, state 1, dim/data2 111
2021-01-30 16:56:05 DBG [plejd-ble] Kök tak (13) got state+dim update. S: 1, D: 111
2021-01-30 16:56:05 VRB [plejd-mqtt] Updating state for Kök tak: 1, dim: 111
2021-01-30 16:56:05 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":111},"14":{"state":1,"dim":168},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:05 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/13/state - {"state":"ON","brightness":111}
2021-01-30 16:56:05 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/13/availability - online
2021-01-30 16:56:05 VRB [plejd-ble] Raw event received: 0d0110009801cb59
2021-01-30 16:56:05 VRB [plejd-ble] Device 13, cmd 0098, state 1, dim/data2 203
2021-01-30 16:56:05 DBG [plejd-ble] Kök tak (13) got state+dim update. S: 1, D: 203
2021-01-30 16:56:05 VRB [plejd-mqtt] Updating state for Kök tak: 1, dim: 203
2021-01-30 16:56:05 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":203},"14":{"state":1,"dim":168},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:05 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/13/state - {"state":"ON","brightness":203}
2021-01-30 16:56:05 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/13/availability - online
2021-01-30 16:56:06 VRB [plejd-ble] Raw event received: 0d0110009801cb5900
2021-01-30 16:56:06 VRB [plejd-ble] Device 13, cmd 0098, state 1, dim/data2 203
2021-01-30 16:56:06 DBG [plejd-ble] Kök tak (13) got state+dim update. S: 1, D: 203
2021-01-30 16:56:06 VRB [plejd-mqtt] Updating state for Kök tak: 1, dim: 203
2021-01-30 16:56:06 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":203},"14":{"state":1,"dim":168},"15":{"state":1,"dim":245},"16":{"state":1,"dim":255},"20":{"state":0,"dim":189},"21":{"state":1,"dim":167},"22":{"state":1,"dim":255},"27":{"state":1,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 16:56:06 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/13/state - {"state":"ON","brightness":203}
2021-01-30 16:56:06 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/13/availability - online```

@SweVictor I suggest you re-open this issue.

**Comment by ankisch** [comment] 2021-01-30 16:22
Unfortunately I'm not at home and had to get my SO to dim the lights while checking the logs from another location. Realized that it is not easy to read from the log and see what's happening with the brightness level and I think that she dimmed both ways. However, when she dimmed the wheel just two clicks down this is what the log is showing then.

On monday I'll be back home and could investigate this further. I might be able to get her to maneuver a dimmer once more if needed though.

```
2021-01-30 17:10:05 VRB [plejd-ble] Raw event received: 0e01100098019891
2021-01-30 17:10:05 VRB [plejd-ble] Device 14, cmd 0098, state 1, dim/data2 152
2021-01-30 17:10:05 DBG [plejd-ble] Kök bänk (14) got state+dim update. S: 1, D: 152
2021-01-30 17:10:05 VRB [plejd-mqtt] Updating state for Kök bänk: 1, dim: 152
2021-01-30 17:10:05 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":185},"14":{"state":1,"dim":152},"15":{"state":1,"dim":53},"16":{"state":1,"dim":255},"17":{"state":1,"dim":53},"20":{"state":0,"dim":189},"21":{"state":1,"dim":158},"22":{"state":1,"dim":255},"27":{"state":0,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 17:10:05 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/14/state - {"state":"ON","brightness":152}
2021-01-30 17:10:05 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/14/availability - online
2021-01-30 17:10:05 VRB [plejd-ble] Raw event received: 010110001be692156001
2021-01-30 17:10:05 VRB [plejd-ble] Device 1, cmd 001b, state NaN, dim/data2 146
2021-01-30 17:10:05 VRB [plejd-ble] Raw event received: 0e01100098015c87
2021-01-30 17:10:05 VRB [plejd-ble] Device 14, cmd 0098, state 1, dim/data2 92
2021-01-30 17:10:05 DBG [plejd-ble] Kök bänk (14) got state+dim update. S: 1, D: 92
2021-01-30 17:10:05 VRB [plejd-mqtt] Updating state for Kök bänk: 1, dim: 92
2021-01-30 17:10:05 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":185},"14":{"state":1,"dim":92},"15":{"state":1,"dim":53},"16":{"state":1,"dim":255},"17":{"state":1,"dim":53},"20":{"state":0,"dim":189},"21":{"state":1,"dim":158},"22":{"state":1,"dim":255},"27":{"state":0,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 17:10:05 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/14/state - {"state":"ON","brightness":92}
2021-01-30 17:10:05 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/14/availability - online
2021-01-30 17:10:06 VRB [plejd-ble] Raw event received: 0e01100098015c8700
2021-01-30 17:10:06 VRB [plejd-ble] Device 14, cmd 0098, state 1, dim/data2 92
2021-01-30 17:10:06 DBG [plejd-ble] Kök bänk (14) got state+dim update. S: 1, D: 92
2021-01-30 17:10:06 VRB [plejd-mqtt] Updating state for Kök bänk: 1, dim: 92
2021-01-30 17:10:06 VRB [plejd-ble] All states: {"11":{"state":1,"dim":208},"13":{"state":1,"dim":185},"14":{"state":1,"dim":92},"15":{"state":1,"dim":53},"16":{"state":1,"dim":255},"17":{"state":1,"dim":53},"20":{"state":0,"dim":189},"21":{"state":1,"dim":158},"22":{"state":1,"dim":255},"27":{"state":0,"dim":120},"29":{"state":0,"dim":197},"30":{"state":0,"dim":102},"33":{"state":0,"dim":204},"34":{"state":0,"dim":3},"41":{"state":0,"dim":210},"42":{"state":0,"dim":96},"43":{"state":1,"dim":210},"46":{"state":0,"dim":65},"47":{"state":0,"dim":102},"49":{"state":0,"dim":255},"50":{"state":0,"dim":255},"53":{"state":0,"dim":255},"54":{"state":0,"dim":229}}
2021-01-30 17:10:06 VRB [plejd-mqtt] State update sent over mqtt to HA homeassistant/light/plejd/14/state - {"state":"ON","brightness":92}
2021-01-30 17:10:06 VRB [plejd-mqtt] Warning: Got unrecognized mqtt command on homeassistant/light/plejd/14/availability - online
2021-01-30 17:10:08 VRB [plejd-mqtt] Got mqtt command on homeassistant/light/plejd/21/set - {"state": "ON", "transition": 45.0, "brightness": 157}
```
