### ISSUE TITLE
Reboot turns on all lights.

### ISSUE THREAD

**Issue by Tozzi89** [icanos/hassio-plejd#218] opened 2021-11-05 22:16 UTC
I have noticed that everytime I reboot/restart my RPI 3 B+, it will turn on all the lights in my home.

Is there a way to not touch current status after reboot?

**Comment by f00dagi** [comment] 2021-11-09 21:03
I have the same issue, when Home Assistant reboots plejd lights controlled by this add-on (randomly?) change state. Some lights turn on while others turn off. Not all lights change state during a reboot.

I have never seen this before moving to latest 0.8.0-beta release (I have not tried to roll-back).

This is a complete show stopper for me, if (for any reason) Home Assistant reboots at night the lights in my kids room (will most likely) be switched on. This also prevents me from doing any controlled reboots after bedtime.

I am at the latest core-2021.11.1 and Home Assistant OS 6.6.

I would really appreciate a solution to this (bug?). Thanks!

**Comment by Tozzi89** [comment] 2021-11-09 22:13
> I have the same issue, when Home Assistant reboots, plejd lights controlled by this add-on (randomly?) change state. Some lights turn on while others turn off. Not all lights change state during a reboot.
> 
> I have never seen this before moving to latest 0.8.0-beta release (I have not tried to roll-back).
> 
> This is a complete show stopper for me, if (for any reason) Home Assistant reboots at night the lights in my kids room (will most likely) be turned on. This also prevents me from doing any controlled reboots after bedtime.
> 
> I am at the latest core-2021.11.1 and Home Assistant OS 6.6 on an Intel NUC.
> 
> I would really appreciate a solution to this (bug?). Thanks for a great add-on!

I turned off autostart for now and start it manually until there is a fix.

**Comment by SweVictor** [comment] 2021-11-10 06:56
Alright, strange. I actually saw a similar issue today. Anyone has any logs to post?

**Comment by Tozzi89** [comment] 2021-11-10 12:45
> Alright, strange. I actually saw a similar issue today. Anyone has any logs to post?

I’m quite new to HA and this all, could you please point to what logs you need exactly?

**Comment by SweVictor** [comment] 2021-11-10 12:57
It's a bit cumbersome to get a full log. You typically need to enable verbose logging in the addon config and follow the https://github.com/icanos/hassio-plejd/tree/master/plejd#logs to extract it all.

**Comment by f00dagi** [comment] 2021-11-12 20:14
In verbose I get lots of log lines that gets lost in the HA web interface, are there anything in particular you are looking for that I should try to capture?

I tried to follow the link instructions but in the terminal I could not successfully runt the container command as per image.

![bild](https://user-images.githubusercontent.com/56124786/141529035-d622f37e-cbe4-4511-9714-00baad969d68.png)

**Comment by thatvalis** [comment] 2021-12-12 23:04
Hi, I also have this problem.
Same rooms are always set to lights on after reboot.
Unfortunately all the bed rooms are included so it is becoming a big problem.
Can try to post logs tomorrow.

**Comment by nysmag** [comment] 2021-12-13 18:49
I also have this issue.
Tried to capture logs when restarting hass but of course lights didn't change then...
So, I restarted the addon and then lights did changed.

Logs

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Config: {
  site: 'Fairlake',
  username: '---scrubbed---',
  password: '---scrubbed---',
  mqttBroker: 'mqtt://192.168.1.11',
  mqttUsername: 'plejd',
  mqttPassword: '---scrubbed---',
  includeRoomsAsLights: false,
  preferCachedApiResponse: true,
  updatePlejdClock: true,
  logLevel: 'debug',
  connectionTimeout: 2,
  writeQueueWaitTime: 400
}
2021-12-13 19:25:26 DBG [plejd-main] Log level set to debug
Starting Plejd addon and reading configuration...
2021-12-13 19:25:26 DBG [plejd-main] Log level set to debug
2021-12-13 19:25:26 INF [plejd-main] Plejd add-on, version 0.8.0-beta
2021-12-13 19:25:27 INF [device-comm] Starting Plejd communication handler.
2021-12-13 19:25:27 INF [plejd-ble] Starting Plejd BLE Handler, resetting all device states.
2021-12-13 19:25:27 INF [plejd-main] Main Plejd addon init()...
2021-12-13 19:25:27 INF [plejd-api] init()
2021-12-13 19:25:27 INF [plejd-api] Getting cached api response from disk
2021-12-13 19:25:27 DBG [plejd-api] Prefer cache? true
2021-12-13 19:25:27 DBG [plejd-api] Cache exists? Yes, created 2021-10-13T12:07:21.813Z
2021-12-13 19:25:27 INF [plejd-api] Cache preferred. Skipping api requests and setting api data to response from 2021-10-13T12:07:21.813Z
2021-12-13 19:25:27 INF [plejd-api] Getting devices from site details response...
2021-12-13 19:25:27 INF [plejd-api] No Plejd gateway found on site
2021-12-13 19:25:27 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
2021-12-13 19:25:27 INF [plejd-ble] init()
2021-12-13 19:25:27 DBG [plejd-ble] Found BLE interface 'org.bluez.Adapter1' at /org/bluez/hci0
2021-12-13 19:25:27 INF [plejd-mqtt] Connected to MQTT.
2021-12-13 19:25:27 INF [plejd-mqtt] Sending discovery for 12 Plejd output devices
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Ovan Vardagsfönster
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Ovan Vardagsfönster (12 : EFD8C867406B_1).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Vardagsfönster
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Vardagsfönster (11 : EFD8C867406B_0).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Fönsteruttag Matsal
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Fönsteruttag Matsal (14 : D9AF0352C8B2_0).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Matsalsfönster
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Matsalsfönster (15 : D9AF0352C8B2_1).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Taklampa
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Taklampa (16 : D8479750A95D_0).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Soffbord
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Soffbord (17 : D8479750A95D_1).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Matbord
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Matbord (19 : DDE882FF2DEF_1).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Altan Extra
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Altan Extra (18 : DDE882FF2DEF_0).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Takspottar
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Takspottar (21 : D9FFE6270296_1).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Köksö
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-02 (light) named Köksö (20 : D9FFE6270296_0).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Hylla
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered CTR-01 (light) named Hylla (22 : EFA6A52D1A08_0).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Fönster
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered DIM-01 (light) named Fönster (24 : F4BE17FC9AA5_0).
2021-12-13 19:25:27 INF [plejd-mqtt] Sending discovery for 0 Plejd input devices
2021-12-13 19:25:27 INF [plejd-mqtt] Sending discovery for 2 Plejd scene devices
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Morgon
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered Scene (scene) named Morgon (1 : 4c1c97f8-c94c-4577-bbfa-2347604cf286).
2021-12-13 19:25:27 DBG [plejd-mqtt] Sending discovery for Natt
2021-12-13 19:25:27 INF [plejd-mqtt] Discovered Scene (scene) named Natt (2 : dd778f53-33c0-49f2-9f45-b72b36e4cd6f).
2021-12-13 19:25:27 INF [device-comm] Plejd got turn on command for Ovan Vardagsfönster (EFD8C867406B_1), brightness undefined
2021-12-13 19:25:27 DBG [device-comm] Queueing turn on Ovan Vardagsfönster (EFD8C867406B_1). No brightness specified, setting DIM to previous.
2021-12-13 19:25:27 INF [device-comm] Plejd got turn on command for Vardagsfönster (EFD8C867406B_0), brightness undefined
2021-12-13 19:25:27 DBG [device-comm] Queueing turn on Vardagsfönster (EFD8C867406B_0). No brightness specified, setting DIM to previous.
2021-12-13 19:25:27 INF [device-comm] Plejd got turn on command for Matsalsfönster (D9AF0352C8B2_1), brightness 76
2021-12-13 19:25:27 DBG [device-comm] Queueing D9AF0352C8B2_1 set brightness to 76
2021-12-13 19:25:27 INF [device-comm] Plejd got turn on command for Taklampa (D8479750A95D_0), brightness undefined
2021-12-13 19:25:27 DBG [device-comm] Queueing turn on Taklampa (D8479750A95D_0). No brightness specified, setting DIM to previous.
2021-12-13 19:25:27 INF [device-comm] Plejd got turn on command for Soffbord (D8479750A95D_1), brightness undefined
2021-12-13 19:25:27 DBG [device-comm] Queueing turn on Soffbord (D8479750A95D_1). No brightness specified, setting DIM to previous.
2021-12-13 19:25:27 INF [device-comm] Plejd got turn on command for Matbord (DDE882FF2DEF_1), brightness undefined
2021-12-13 19:25:27 DBG [device-comm] Queueing turn on Matbord (DDE882FF2DEF_1). No brightness specified, setting DIM to previous.
2021-12-13 19:25:27 INF [device-comm] Plejd got turn off command for Altan Extra (DDE882FF2DEF_0)
2021-12-13 19:25:27 DBG [device-comm] Queueing turn off DDE882FF2DEF_0
2021-12-13 19:25:27 INF [device-comm] Plejd got turn on command for Takspottar (D9FFE6270296_1), brightness 61
2021-12-13 19:25:27 DBG [device-comm] Queueing D9FFE6270296_1 set brightness to 61
2021-12-13 19:25:27 INF [device-comm] Plejd got turn off command for Köksö (D9FFE6270296_0)
2021-12-13 19:25:27 DBG [device-comm] Queueing turn off D9FFE6270296_0
2021-12-13 19:25:27 INF [device-comm] Plejd got turn on command for Hylla (EFA6A52D1A08_0), brightness 112
2021-12-13 19:25:27 DBG [device-comm] Queueing EFA6A52D1A08_0 set brightness to 112
2021-12-13 19:25:27 INF [device-comm] Plejd got turn off command for Fönster (F4BE17FC9AA5_0)
2021-12-13 19:25:27 DBG [device-comm] Queueing turn off F4BE17FC9AA5_0
2021-12-13 19:25:32 INF [plejd-ble] disconnecting /org/bluez/hci0/dev_EF_D8_C8_67_40_6B. This can take up to 180 seconds
2021-12-13 19:25:34 INF [plejd-ble] BLE init done, waiting for devices.
2021-12-13 19:25:34 INF [plejd-main] Main init done
2021-12-13 19:25:34 INF [plejd-main] main() finished
2021-12-13 19:25:34 DBG [plejd-ble] Found Plejd service on /org/bluez/hci0/dev_D8_47_97_50_A9_5D
2021-12-13 19:25:34 DBG [plejd-ble] initDiscoveredPlejdDevice(). Got /org/bluez/hci0/dev_D8_47_97_50_A9_5D device
2021-12-13 19:25:34 DBG [plejd-ble] Inspecting /org/bluez/hci0/dev_D8_47_97_50_A9_5D
2021-12-13 19:25:34 DBG [plejd-ble] Discovered /org/bluez/hci0/dev_D8_47_97_50_A9_5D with rssi -89 dBm, name undefined
2021-12-13 19:25:36 INF [plejd-ble] Device discovery done, found 1 Plejd devices
2021-12-13 19:25:36 INF [plejd-ble] Connecting to /org/bluez/hci0/dev_D8_47_97_50_A9_5D
2021-12-13 19:25:47 INF [plejd-ble] onDeviceConnected()
2021-12-13 19:25:47 DBG [plejd-ble] Device /org/bluez/hci0/dev_D8_47_97_50_A9_5D, {"deviceId":"D8479750A95D","siteId":"---scrubbed---","title":"Soffbord","traits":11,"hiddenFromRoomList":false,"roomId":"a1975caa-f1c7-4ced-9eae-073b538d549a","createdAt":"2019-10-07T17:28:42.309Z","updatedAt":"2019-10-27T19:23:31.760Z","ACL":{},"objectId":"vxsFDQoq0g","__type":"Object","className":"Device"}
2021-12-13 19:25:47 INF [plejd-ble] Connected device is a Plejd device with the right characteristics.
2021-12-13 19:25:47 INF [plejd-ble] authenticate()
2021-12-13 19:25:47 DBG [plejd-ble] Sending challenge to device
2021-12-13 19:25:47 DBG [plejd-ble] Reading response from device
2021-12-13 19:25:47 DBG [plejd-ble] Responding to authenticate
2021-12-13 19:25:47 INF [plejd-ble] BLE Connected to undefined
2021-12-13 19:25:47 INF [plejd-ble] Requesting current Plejd time...
2021-12-13 19:25:47 INF [plejd-ble] startPing()
2021-12-13 19:25:47 INF [device-comm] Bluetooth connected. Plejd BLE up and running!
2021-12-13 19:25:47 INF [device-comm] startWriteQueue()
2021-12-13 19:25:48 DBG [device-comm] Write queue: Processing Ovan Vardagsfönster (EFD8C867406B_1). Command Turn on. Total queue length: 10
2021-12-13 19:25:48 DBG [device-comm] Write queue: Processing Vardagsfönster (EFD8C867406B_0). Command Turn on. Total queue length: 9
2021-12-13 19:25:48 DBG [device-comm] Write queue: Processing Matsalsfönster (D9AF0352C8B2_1). Command Dim 76. Total queue length: 8
2021-12-13 19:25:48 DBG [device-comm] Write queue: Processing Taklampa (D8479750A95D_0). Command Turn on. Total queue length: 7
2021-12-13 19:25:48 DBG [device-comm] Write queue: Processing Soffbord (D8479750A95D_1). Command Turn on. Total queue length: 6
2021-12-13 19:25:48 DBG [device-comm] Write queue: Processing Matbord (DDE882FF2DEF_1). Command Turn on. Total queue length: 5
2021-12-13 19:25:48 DBG [device-comm] Write queue: Processing Altan Extra (DDE882FF2DEF_0). Command Turn off. Total queue length: 4
2021-12-13 19:25:48 DBG [device-comm] Write queue: Processing Takspottar (D9FFE6270296_1). Command Dim 61. Total queue length: 3
2021-12-13 19:25:48 DBG [device-comm] Write queue: Processing Köksö (D9FFE6270296_0). Command Turn off. Total queue length: 2
2021-12-13 19:25:49 DBG [device-comm] Write queue: Processing Hylla (EFA6A52D1A08_0). Command Dim 112. Total queue length: 1
2021-12-13 19:25:49 DBG [device-comm] Write queue: Processing Fönster (F4BE17FC9AA5_0). Command Turn off. Total queue length: 0

fyi, the scenes do not exist in the app (removed them some days ago).

Before the restart of the addon
"Taklampa (D8479750A95D_0)" was not on, was turned on by the addon.
"Takspottar (21 : D9FFE6270296_1)" didn't have brightness 61, was much lower.

**Comment by thatvalis** [comment] 2022-01-03 06:37
I have had some reboots now where this issue does not appear anymore.
Since I last wrote here I have been updating HA, but I also uninstalled Zigbee2mqtt from HA and moved it to its own RPI.
Maybe that can have something to do with it?

**Comment by thatvalis** [comment] 2022-01-07 06:09
Hi again.
False alarm, behaviour still exists but it is different lights that get turned on / turned off now.
It seems the add-on remembers a state, and when it is reloaded it goes back to that state.
So at some point my add-on updated its state, which changed which lights now get turned on / turned off.

**Comment by SweVictor** [comment] 2022-04-10 09:57
I looked a bit in the code. The lines similar to `Plejd got turn on command for Ovan Vardagsfönster (EFD8C867406B_1), brightness undefined` are generated from received mqtt commands. My guess would be that Home Assistant has a state for a device that gets pushed to the Plejd device on startup of the addon. 

Can anyone confirm that? Presumably, this would show this behavior:
1. Set lamp to on in HA => Lamp turns on
2. Turn off plejd addon
3. Set lamp to off in plejd app => Lamp turns off, state in HA = on
4. Turn on plejd addon
5. My guess is that the HA state is "on" an this will be sent to the plejd addon on startup => Lamp turns on again

**Comment by mudape** [comment] 2022-04-10 15:15
Hi,
Yes I can confirm.

1. 'Takspottar (D9FFE6270296_1)' is turned on in HA.
2. Stopped the addon.
3. Turned the light off via wall switch.
4. Started addon and light turns on.

Also changed brightness for 'Matbord (DDE882FF2DEF_1)' when addon was stopped.
That didn't change when starting the addon. (undefined brightness, previous used)

plejd_1.log before stopping, plejd_2.log after starting again.

[plejd_1.log](https://github.com/icanos/hassio-plejd/files/8459253/plejd_1.log)
[plejd_2.log](https://github.com/icanos/hassio-plejd/files/8459254/plejd_2.log)

**Comment by SweVictor** [comment] 2022-04-10 15:42
So... Is this a feature or a bug? 🙂

And, how should we handle this?

**Comment by Tozzi89** [comment] 2022-04-10 16:06
I have moved to a physical server running proxmox. I don’t see this behaviour there, only on Raspberry Pi. I tried the same at my brother place at he has the samme issue on Raspberry Pi, but not when running HA image in proxmox. Is the states not saved correctly to SD card during reboot or are the bluetooth module doing something?

**Comment by mudape** [comment] 2022-04-10 18:53
> So... Is this a feature or a bug? 🙂
> 
> And, how should we handle this?

I'd say bug as state of plejd device is changed by the addon on startup.
Looks to me like the addon acts on a mqtt message which doesn't reflect the current state.

Maybe check the message timestamp (if available) and if it's older then the addons startup time, ignore it?
The current state should be known by Plejd, not MQTT (?)

I'm running the addon on a Raspberry 4, MQTT (eclipse-mosquitto) in docker on another machine.

**Comment by SweVictor** [comment] 2022-04-11 06:53
> I'd say bug as state of plejd device is changed by the addon on startup. Looks to me like the addon acts on a mqtt message which doesn't reflect the current state.
> 
> Maybe check the message timestamp (if available) and if it's older then the addons startup time, ignore it? The current state should be known by Plejd, not MQTT (?)

Hmm.... In `init()` in `MqttClient` we set up the mqtt connection. using the https://github.com/mqttjs/MQTT.js lib. To allow for multiple Plejd addons (on separate machines) we randomize the client id. I'm guessing the reason we see this behavior is that
1. Mosquitto retains messages (as they represent the state of each device)
2. We create a new client id
3. We therefore get the state echoed to us when starting (since we're a new client)

Mosquitto _has_ been updated to support mqtt v5 nowadays, so we could work with persistence and QoS a bit more. It is, however, quite a complex topic to figure out all side effects around. We could also replace the random client id with something else (config setting for example).

Either way the wanted behavior is not 100% clear here. Currently, since we're reading "last known state", we're getting a state of all devices that are "80% right" (let's say). If we stop reading the state at startup, we'll get "100% unknown". Is that really better?

The more advanced route is to query the plejd mesh for the state of each device on startup. See https://github.com/klali/ha-plejd/commit/de1333460dcb67750a22357dc60064db012a61eb for inspiration.

Up for grabs if someone wants to look into this and create a PR to the develop branch.

**Comment by Tozzi89** [comment] 2022-04-12 13:57
I think it is better to ask current state at startup instead of asuming last state and change current status everytime the addon starts.

**Comment by xpatohr** [comment] 2022-07-14 08:50
> I think it is better to ask current state at startup instead of asuming last state and change current status everytime the addon starts.

Totally agree with that.
My lights were on when I got home after the weekend. Because HA has been upgraded when i was away. Plejd should be a master of the current status.

**Comment by pissten** [comment] 2022-10-10 05:42
+1 on query plejd mesh for state on startup

**Comment by spripe** [comment] 2022-10-11 21:01
I also totally agree to ask for current state during startup

**Comment by TheBigDaddyT** [comment] 2022-11-29 11:05
+1 woke up last week because the house lit up

**Comment by igalg99** [comment] 2022-12-02 18:34
so over 1 year passed since this issue has opened and no fix I see.
I am having same problem. it sort of remembers the state of the lights. every now and then the memory changes to different lights.

**Comment by johanfrick** [comment] 2023-02-12 20:12
I have the same problem. Any workarounds available for this?

**Comment by pierrei** [comment] 2023-03-12 17:15
Suggesting a fix for this here: https://github.com/icanos/hassio-plejd/pull/268.

**Comment by pierrei** [comment] 2023-03-19 19:48
I did some investigating and it turns out the problem comes from the fact that startup of this add-on goes as follows (among other things):
1. Connect to MQTT
2. Listen to the connect event
3. Listen to incoming message
4. Connected to MQTT: start "HA discovery"
5. Send a bunch of updates to MQTT
6. MQTT Messages received -> lights changed!

We can't both listen to changes from MQTT while at the same time send updates. I have created a PR with a fix that makes sure to ignore any messages from MQTT while discovery is happening.

https://github.com/icanos/hassio-plejd/pull/268

**Comment by henningms** [comment] 2023-06-21 20:34
Any updates on this?

**Comment by pierrei** [comment] 2023-06-21 21:20
@henningms Seems like the owner of this project is not very active and so nothing is happening. My branch (https://github.com/icanos/hassio-plejd/pull/268) is working for me and I'm running it with my Home Assistant at home.

**Comment by SweVictor** [comment] 2023-08-18 11:01
Elaborating a bit on the comment in the release thread.

To me, it seems like the consensus in this thread and others is that the most sensible thing to do is to trust the state in the Plejd mesh rather than the state in HA/MQTT.

To me, that makes sense. The issues we had previously with this addon crashing often are gone (afaik), meaning normally the addon will be always on. In the rare case it crashes and gets rebooted, that should take less than a minute. We can probably safely disregard any changes made in HA during that period of time.

This leaves state changes when the HA is offline/restarting (also meaning the addon restarts). This could be prolonged periods of time for different reason, and again, the user is presumably more happy with the current state of the actual physical lamps than the state HA saved some time ago.

Given the above, I think quite a few changes in the code need to happen:
* Lower the QoS in MQTT - based on the above it seems to me like we _do not_ want to save any state in the MQTT "memory". Any new or newly started Plejd addons will start from zero
* Query the Plejd mesh at startup. Presumably, this is PR #260, although I think the code needs to be improved and (above all) tested
* (disregard early state changes, possibly PR #268. Personally, I don't think this should be needed if MQTT does not have a memory, but it still might be reasonable to implement Startup => Get state from Plejd mesh => Wait for "a while" before accepting incoming state changes, but the "a while" is quite tricky. I don't think we can be sure we actually get a state update for every device)

**Comment by timjackson** [comment] 2023-08-18 11:20
Agree fully with the [analysis](https://github.com/icanos/hassio-plejd/issues/218#issuecomment-1683747009). In particular, the "real" (physical) state ought to take precedence over saved state. I'd rather that some entities in HA were out of sync rather than turning things on/off when they shouldn't. I haven't tested #260 (or #268 for that matter) but am willing to do so if the consensus is that it's the right way to go.

**Comment by Mats1717** [comment] 2023-09-11 09:17
I found this one and it works prefectly for me.
https://github.com/tomjaimz/hassio-plejd

**Comment by henningms** [comment] 2023-09-11 11:01
> 
> Given the above, I think quite a few changes in the code need to happen:
> 
> * Lower the QoS in MQTT - based on the above it seems to me like we _do not_ want to save any state in the MQTT "memory". Any new or newly started Plejd addons will start from zero
> * Query the Plejd mesh at startup. Presumably, this is PR [Integrated current state fetch from plejd mesh #260](https://github.com/icanos/hassio-plejd/pull/260), although I think the code needs to be improved and (above all) tested
> * (disregard early state changes, possibly PR [MQTT startup bugfix #268](https://github.com/icanos/hassio-plejd/pull/268). Personally, I don't think this should be needed if MQTT does not have a memory, but it still might be reasonable to implement Startup => Get state from Plejd mesh => Wait for "a while" before accepting incoming state changes, but the "a while" is quite tricky. I don't think we can be sure we actually get a state update for every device)

Do all three things have to happen in the same release? Or would it be faster to release one with just the QoS and then do some proper work on the rest (or decide to merge the PRs)?

**Comment by SweVictor** [comment] 2023-11-12 14:34
So, after the BLE issues were fixed in the new HAOS release I've done some more digging using MQTT Explorer to look into the MQTT messages in-depth.

I wrote a huge post here, but deleted it after figuring out what actually happens 😄 

_TLDR:_ Too much info is retained in MQTT. Both by the addon _and by HA_!

# Background
For each Plejd light we add to HA there are 4 relevant mqtt topics:
* Config: Set by **us** describing the device and its topics
* Availability: Set by **us** (online/offline)
* State: Set by **us** (state = on/off, brightness, ...)
* Set: Set by **HA** to set the "wanted state"

As of v0.11 _all_ of the above messages are _retained_ in the mqtt broker (often Mosquitto), meaning _every new device that connects to Mosquitto will receive the last known value_. 

This gives two issues:
1. When HA starts up, it will receive _our_ retained  `state` value and set that as the state for the light. This could, potentially, be very old, just retained by the mqtt broker.
2. When the addon starts up, it will receive _HA:s_ retained `set` value _and send that state to the light_

In my opinion, both HA and we are in the wrong here, but the issues we mainly see are due to (2), meaning due to HA.

Really, only _config_ should be retained, _but since we cannot affect that HA sets `retain = true` for set messages we need to work around that_.

# Fixing the problem

## Fixing our side

To fix our side, we should set `retain = false` on all mqtt messages except config ones. I'm implementing this fix in a separate branch.

## Fixing the HA side

Since we can't change HA:s behavior we need to do a fix similar to @pierrei in #268. 

Basically, we need to ignore the first (retained) SET message that comes in from the MQTT broker for each device, but process all subsequent messages. I don't necessarily like the way of fixing it in the PR "probably, the retained messages will have been delivered after 3 seconds". 

# Potential ways to fix the issue

## Retained messages

To remove a retained message in mqtt we need to _publish a blank message to the right topic with `retain = true`_ (somewhat counter-intuitively).

We could therefore, potentially, reverse the order in which we do things during startup. 

### Today we:

1. Set up mqtt subscriptions to be able to receive all messages immediately
2. Connect to the mqtt broker
3. Publish _config_ messages only
4. Receive all retained messages
5. Publish our own messages

### We could instead

1. Connect to the mqtt broker
2. Publish _config_ messages with `retain = true`
3. Publish messages to forcefully remove all state, availability, and (most importantly) SET messages
4. (By now the mqtt broker should be empty apart from config messages.
5. (preferably wait until BLE communication starts)
6. Send availability = online
7. Publish updates on new state updates

Basically we would, on every addon startup, clear any existing state and force HA to start from a blank state that we define (for Plejd).

**Comment by SweVictor** [comment] 2023-11-12 15:48
# Current state 

Typical (retained) state in v0.11 looks like this in MQTT Explorer:
![image](https://github.com/icanos/hassio-plejd/assets/449347/bd7795ba-9ed0-4485-a962-c3f0a4b55382)

We would like to only see the Config message retained.


# Fix part 1

I have tried to implement the fix outlined in "we could instead" in the previous message in 
https://github.com/icanos/hassio-plejd/tree/feature/improve-startup-behavior

## Result

### 1. Device set to fully ON in HA

![image](https://github.com/icanos/hassio-plejd/assets/449347/8c8026a6-0832-4c24-a72d-f1786869d15b)

### 2. Shut down Plejd addon, change state in Plejd app to OFF

(no change in mqtt)

### 3. Start Plejd addon

(previously this would change state to fully on again)

MQTT retained messages are removed during startup
![image](https://github.com/icanos/hassio-plejd/assets/449347/b7e9f4d8-983e-4393-9cd1-226da0136bbe)

Once online again:
![image](https://github.com/icanos/hassio-plejd/assets/449347/adc7d74b-bbdf-42f9-a09a-edbce9daa93f)

### 4. But not really

While the above looks very good and the logs look good, the result is still that the retained messages that were deleted are processed.

Looking in the code, my guess is that:

1. In MqttClient we _wait for an incoming message_ (normally retained) to indicate that Home Assistant has started. 
2. We _then_ start discovery (in which we delete retained messages).

Given the mqtt broker's capability to retain messages it seems like we could simply skip this step and rather

1. Send discovery of devices immediately after mqtt is up and we have a response from the api
2. Delete retained messages
3. AFTER that start listening to incoming messages
4. (we then may want to to retain AVAILABILITY messages as well)

# Fix part 2

After implementing the above flow and also skipping the HA birth message **it kinda works!**

## Remaining issues

Looking at the MQTT messages, the state of most devices aren't known. (Plejd will address this eventually through devices sending their state from time to time, but it will take a long time).

During this "unknown" state, it is quite clear that HA internally also stores a last known state per device. Devices are shown as available and showing the state HA was last aware of (since no update exists on mqtt anymore).

Apart from that, _the state is no longer changed during startup_ which is great.

A second potential issue is the removal of the listening to HA startup message. IF the addon starts before HA (which will probably only happen when the MQTT broker is running separately from HA) this will/may result in CONFIG messages being lost at first startup, meaning no devices are shown. It may also lead to strange availability and state messages.

Fix part 3 yet to come, but if anyone wants to to verify that the current code version in https://github.com/icanos/hassio-plejd/tree/feature/improve-startup-behavior indeed does not change the lights' status on startup feel free to do so!

**Comment by SweVictor** [comment] 2023-11-19 09:55
# Fix part 3
Done!

Emit discovery messages both when connecting to MQTT and when Home Assistant sends birth message
Why? Well, birth messages by default are not retained by HA.

When digging around I also saw that HA seems to default to MQTT version 5 (we do send some v5-specific flow control nowadays). Just an FYI.

Anyway - this fix is complete and will be merged to the [develop](https://github.com/icanos/hassio-plejd/tree/develop) branch shortly. 

**Please try that fix using a manual install if you have the chance** before we push it as a public release.

Closing this for now, but feel free to reopen if this does not solve the core issue.

**Closed by SweVictor** 2023-11-19 09:55 UTC
Labels: help wanted
